import data from "@/data/dictionaries.json";
import type { Lang } from "@/lib/dictionary";

/**
 * Short English adjectives ("modifiers") used to bias domain candidates
 * toward modifier+noun pairs (e.g. "swiftfox") instead of two arbitrary
 * nouns jammed together (e.g. "hogorb") — the former reads as an
 * intentional brand name, the latter as two random words.
 *
 * Generated by scripts/build-dictionaries.mjs, which POS-tags the WordNet-
 * sourced dictionary against WordNet's own adjective index (index.adj) —
 * a word with a recognized adjective sense counts as a modifier.
 */
const MODIFIERS_BY_LANG: Record<Lang, Set<string>> = {
  english: new Set(data.englishModifiers),
};

/**
 * langs is currently always a single-element ["english"] array (see
 * lib/dictionary.ts), but kept as an array so this signature doesn't need
 * to change if another language is ever added back.
 */
export function isModifier(word: string, langs: Lang[]): boolean {
  return langs.some((lang) => MODIFIERS_BY_LANG[lang].has(word));
}
